services:
  # PostgreSQL Database for User Service
  user-db:
    container_name: user-db-pgsql
    image: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - userdb-data:/var/lib/postgresql/data

  # PostgreSQL Database for Inventory Service
  inventory-db:
    container_name: inventory-db-pgsql
    image: postgres
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - inventorydb-data:/var/lib/postgresql/data

  # PostgreSQL Database for Order Service
#  order-db:
#    container_name: order-db-pgsql
#    image: postgres
#    environment:
#      POSTGRES_DB: orderdb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5434:5432"
#    volumes:
#      - orderdb-data:/var/lib/postgresql/data

  # Redis for session management
  redis:
    image: redis:8.0.0-alpine
    ports:
      - "6379:6379"

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
    depends_on:
      - user-db
      - redis

  # Inventory Service
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      USER_SERVICE_URL: http://user-service:8081
    depends_on:
      - inventory-db
      - user-service

  # Order Service
#  order-service:
#    build:
#      context: ./order-service
#      dockerfile: Dockerfile
#    ports:
#      - "8083:8083"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      USER_SERVICE_URL: http://user-service:8081
#      INVENTORY_SERVICE_URL: http://inventory-service:8082
#    depends_on:
#      - order-db
#      - user-service
#      - inventory-service

volumes:
  userdb-data:
  inventorydb-data:
#  orderdb-data: